In [1]:
import os
import sys

root_dir = os.path.abspath("..")
if root_dir not in sys.path:
    sys.path.append(root_dir)

In [2]:
from model.model import EcoModel
from model.accounts import FINANCIAL_ASSETS, TRANSACTIONS

In [3]:
params = {
    "country_number": 2,
    "household_number": 10,
    "psi": 10,
    "upsilon": 1.0,
    "omega": 0.1,
    "initial_wage": 1.0,
    "initial_phi": 1.0,
    "initial_tax_rate": 0.4,
    "cy": 0.9,
    "cd": 0.2,
    "delta": 0.03,
    "cT": 0.4,
    "beta": 2.0,
    "lambda_": 0.2,
    "theta": 0.2,
    "gamma": 0.03,
    "nu": 1.5,
    "rho": 0.95,
    "zeta": 0.1,
    "mu1": 20,
    "mu2": 0.1,
    "iota_l": 1.0,
    "chi": 0.003,
    "iota_b": 0.1,
    "initial_discount_rate": 0.0,
    "initial_bond_rate": 0.001,
    "long_run_rate": 0.0075,
    "xi": 0.8,
    "xi_deltap": 2,
    "inflation_target": 0.005,
    "initial_public_transfer": 0.4,
    "dmax": 0.03,
    "tax_min": 0.35,
    "tax_max": 0.45,
    "g_min": 0.4,
    "g_max": 0.6,
    "eta": 0.03,
    "initial_equity": 10.0,
    "sigma": 4,
}

In [4]:
params["steps"] = 20
model = EcoModel(params)
model.run(seed=1)

defaulted firms []
defaulted banks []
Completed: 1 steps
defaulted firms []
defaulted banks []
Completed: 2 steps
defaulted firms []
defaulted banks []
Completed: 3 steps
defaulted firms []
defaulted banks []
Completed: 4 steps
defaulted firms []
defaulted banks []
Completed: 5 steps
defaulted firms []
defaulted banks []
Completed: 6 steps
defaulted firms []
defaulted banks []
Completed: 7 steps
defaulted firms []
defaulted banks []
Completed: 8 steps
defaulted firms []
defaulted banks []
Completed: 9 steps
defaulted firms []
defaulted banks []
Completed: 10 steps
defaulted firms []
defaulted banks []
Completed: 11 steps
defaulted firms []
defaulted banks []
Completed: 12 steps
defaulted firms []
defaulted banks []
Completed: 13 steps
defaulted firms []
defaulted banks []
Completed: 14 steps
defaulted firms []
defaulted banks []
Completed: 15 steps
defaulted firms []
defaulted banks []
Completed: 16 steps
defaulted firms []
defaulted banks []
Completed: 17 steps
defaulted firms []
defaulted banks []
Completed: 18 steps
defaulted firms []
defaulted banks [Bank (Obj 39)]
Completed: 19 steps
defaulted firms []
defaulted banks []
Completed: 20 steps
Run time: 0:00:00.439006
Simulation finished

DataDict {
'info': Dictionary with 9 keys
'parameters':
    'constants': Dictionary with 40 keys
'variables':
    'Household': DataFrame with 19 variables and 420 rows
    'Government': DataFrame with 19 variables and 42 rows
    'CentralBank': DataFrame with 19 variables and 63 rows
    'Firm': DataFrame with 19 variables and 646 rows
    'Bank': DataFrame with 19 variables and 36 rows
'reporters': DataFrame with 1 variable and 1 row
}

In [5]:
data = model.output.arrange_variables()
data.head()

,obj_type,obj_id,t,deposits,loans,bonds,cash,advances,equities,inventories,...,public_transfers,taxes,dep_interests,loan_interests,loan_defaults,bond_interests,cash_interests,adv_interests,dividends,profit_transfers
0,Household,13,0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Household,13,1,0.0,0.0,0.0,0.40,0.0,0.00,0.0,...,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Household,13,2,0.0,0.0,0.0,-0.48,0.0,1.28,0.0,...,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Household,13,3,0.0,0.0,0.0,-0.08,0.0,1.28,0.0,...,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Household,13,4,0.0,0.0,0.0,0.32,0.0,1.28,0.0,...,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
data[data["obj_id"] == 39]

,obj_type,obj_id,t,deposits,loans,bonds,cash,advances,equities,inventories,...,public_transfers,taxes,dep_interests,loan_interests,loan_defaults,bond_interests,cash_interests,adv_interests,dividends,profit_transfers
1171,Bank,39,7,-3.201323,0.0,0.0,45.760000,0.0,-42.558677,0.0,...,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1172,Bank,39,8,35.198285,0.0,0.0,7.360865,0.0,-42.558205,0.0,...,0.0,0.000000,0.002267,0.000000e+00,-0.001794,0.0,0.0,0.000000,0.000000,0.000473
1173,Bank,39,9,122.464901,0.0,0.0,-79.910947,0.0,-42.558361,0.0,...,0.0,0.000000,-0.003152,0.000000e+00,-0.002043,0.0,0.0,0.000000,0.000000,-0.000156
1174,Bank,39,10,323.656209,0.0,0.0,-280.975701,0.0,-42.425977,0.0,...,0.0,-0.002078,-0.022869,-3.958572e-04,0.000000,0.0,0.0,0.154857,-0.002961,0.132384
1175,Bank,39,11,716.168411,0.0,0.0,-673.018006,0.0,-41.956080,0.0,...,0.0,0.000000,-0.056768,-6.924044e-08,0.000000,0.0,0.0,0.526664,0.000000,0.469897
1176,Bank,39,12,1109.825260,0.0,0.0,-1065.435978,0.0,-40.717202,0.0,...,0.0,0.000000,-0.134705,0.000000e+00,0.000000,0.0,0.0,1.373583,0.000000,1.238878
1177,Bank,39,13,1204.718663,0.0,0.0,-1158.366633,0.0,-38.754455,0.0,...,0.0,0.000000,-0.207321,0.000000e+00,0.000000,0.0,0.0,2.170069,0.000000,1.962748
1178,Bank,39,14,2425.073852,0.0,0.0,-2376.436007,0.0,-36.468639,0.0,...,0.0,0.000000,-0.240800,0.000000e+00,0.000000,0.0,0.0,2.526617,0.000000,2.285816
1179,Bank,39,15,4763.563580,0.0,0.0,-4710.233364,0.0,-31.776268,0.0,...,0.0,0.000000,-0.481908,0.000000e+00,0.000000,0.0,0.0,5.174278,0.000000,4.692370
1180,Bank,39,16,2160.589333,0.0,0.0,-2097.462080,0.0,-21.979230,0.0,...,0.0,0.000000,-0.994023,0.000000e+00,0.000000,0.0,0.0,10.791061,0.000000,9.797038
1181,Bank,39,17,5094.608844,0.0,0.0,-5027.120605,0.0,-17.618245,0.0,...,0.0,0.000000,-0.452456,0.000000e+00,0.000000,0.0,0.0,4.813441,0.000000,4.360985
1182,Bank,39,18,13818.425757,0.0,0.0,-13740.059587,0.0,-6.740314,0.0,...,0.0,0.000000,-1.105754,0.000000e+00,0.000000,0.0,0.0,11.983685,0.000000,10.877931
1183,Bank,39,19,-14.084904,0.0,0.0,134.318164,0.0,22.996388,0.0,...,0.0,0.000000,-2.993986,0.000000e+00,12.130389,0.0,0.0,32.730687,0.000000,29.736701

In [6]:
df2 = data.groupby(["t", "obj_type"]).sum()
df2

                obj_id       deposits  loans       bonds           cash  \
t  obj_type
0  CentralBank     108       0.000000    0.0    0.000000       0.000000
   Government       67       0.000000    0.0    0.000000       0.000000
   Household       450       0.000000    0.0    0.000000       0.000000
1  CentralBank     108       0.000000    0.0    0.000000       0.000000
   Government       67       0.000000    0.0    0.000000      -8.000000
...                ...            ...    ...         ...            ...
20 Bank            388  104898.186833    0.0    0.000000 -100130.523073
   CentralBank     108       0.000000    0.0  104.863815    -539.776597
   Firm           6998      24.543901    0.0    0.000000  100586.573153
   Government       67       0.000000    0.0 -104.863815     -50.591647
   Household       450 -104908.645830    0.0    0.000000       0.000000

                    advances       equities  inventories  consumption  wages  \
t  obj_type
0  CentralBank  0.000000e+00       0.000000          0.0          0.0    0.0
   Government   0.000000e+00       0.000000          0.0          0.0    0.0
   Household    0.000000e+00       0.000000          0.0          0.0    0.0
1  CentralBank  0.000000e+00       0.000000          0.0          0.0    0.0
   Government   0.000000e+00       0.000000          0.0          0.0    0.0
...                      ...            ...          ...          ...    ...
20 Bank         0.000000e+00   -4111.775468          0.0          0.0    0.0
   CentralBank -1.455192e-11       0.000000          0.0          0.0    0.0
   Firm         0.000000e+00 -100611.110091          0.0          0.0    0.0
   Government   0.000000e+00       0.000000          0.0          0.0    0.0
   Household    0.000000e+00  104699.889171          0.0          0.0    0.0

                public_transfers     taxes  dep_interests  loan_interests  \
t  obj_type
0  CentralBank               0.0  0.000000       0.000000             0.0
   Government                0.0  0.000000       0.000000             0.0
   Household                 0.0  0.000000       0.000000             0.0
1  CentralBank               0.0  0.000000       0.000000             0.0
   Government               -8.0  0.000000       0.000000             0.0
...                          ...       ...            ...             ...
20 Bank                      0.0  0.000000     -15.516575             0.0
   CentralBank               0.0  0.000000       0.000000             0.0
   Firm                      0.0  0.000000      -0.002335             0.0
   Government               -8.0  6.207564       0.000000             0.0
   Household                 8.0 -6.207564      15.518909             0.0

                loan_defaults  bond_interests  cash_interests  adv_interests  \
t  obj_type
0  CentralBank       0.000000        0.000000             0.0       0.000000
   Government        0.000000        0.000000             0.0       0.000000
   Household         0.000000        0.000000             0.0       0.000000
1  CentralBank       0.000000        0.000000             0.0       0.000000
   Government        0.000000        0.000000             0.0       0.000000
...                       ...             ...             ...            ...
20 Bank             -0.002335        0.000000             0.0     161.536235
   CentralBank       0.000000        0.052431             0.0    -161.536235
   Firm              0.002335        0.000000             0.0       0.000000
   Government        0.000000       -0.052431             0.0       0.000000
   Household         0.000000        0.000000             0.0       0.000000

                dividends  profit_transfers
t  obj_type
0  CentralBank        0.0          0.000000
   Government         0.0          0.000000
   Household          0.0          0.000000
1  CentralBank        0.0          0.000000
   Government         0.0          0.000000
...                   ...               ...
20 Bank               0.0        146.486623
   CentralBank        0.0         -0.052431
   Firm               0.0          0.002335
   Government         0.0          0.052431
   Household          0.0       -146.488958

[96 rows x 20 columns]

In [7]:
df2.loc[8]

,obj_id,deposits,loans,bonds,cash,advances,equities,inventories,consumption,wages,public_transfers,taxes,dep_interests,loan_interests,loan_defaults,bond_interests,cash_interests,adv_interests,dividends,profit_transfers
obj_type,,,,,,,,,,,,,,,,,,,,
Bank,39,35.198285,0.0,0.000000,7.360865,0.0,-42.558205,0.0,0.0,0.0,0.0,0.000000,0.002267,0.0,-0.001794,0.0,0.0,0.0,0.0,0.000473
CentralBank,108,0.000000,0.0,0.000378,-0.000378,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
Firm,248,12.155812,0.0,0.000000,56.639324,0.0,-68.793342,0.0,0.0,0.0,0.0,0.000000,-0.001794,0.0,0.001794,0.0,0.0,0.0,0.0,0.001794
Government,67,0.000000,0.0,-0.000378,-63.999811,0.0,0.000000,0.0,0.0,0.0,-8.0,-0.000189,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
Household,450,-47.354097,0.0,0.000000,0.000000,0.0,111.351547,0.0,0.0,0.0,8.0,0.000189,-0.000473,0.0,0.000000,0.0,0.0,0.0,0.0,-0.002267

In [8]:
df2.loc[8].sum().map(lambda x: round(x, 4))

obj_id              912.0
deposits              0.0
loans                 0.0
bonds                 0.0
cash                  0.0
advances              0.0
equities              0.0
inventories           0.0
consumption           0.0
wages                 0.0
public_transfers     -0.0
taxes                -0.0
dep_interests         0.0
loan_interests        0.0
loan_defaults         0.0
bond_interests        0.0
cash_interests        0.0
adv_interests         0.0
dividends             0.0
profit_transfers      0.0
dtype: float64

In [9]:
df2.loc[9]

,obj_id,deposits,loans,bonds,cash,advances,equities,inventories,consumption,wages,public_transfers,taxes,dep_interests,loan_interests,loan_defaults,bond_interests,cash_interests,adv_interests,dividends,profit_transfers
obj_type,,,,,,,,,,,,,,,,,,,,
Bank,39,122.464901,0.0,0.000000,-79.910947,0.0,-42.558361,0.0,0.0,0.0,0.0,0.000000,-0.003152,0.0,-0.002043,0.000000e+00,0.0,0.0,0.0,-1.558580e-04
CentralBank,108,0.000000,0.0,0.000567,-0.000567,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,1.890061e-07,0.0,0.0,0.0,-1.890061e-07
Firm,584,25.993870,0.0,0.000000,151.908340,0.0,-177.898372,0.0,0.0,0.0,0.0,0.000000,-0.003837,0.0,0.002043,0.000000e+00,0.0,0.0,0.0,3.837262e-03
Government,67,0.000000,0.0,-0.000567,-71.996826,0.0,0.000000,0.0,0.0,0.0,-8.0,0.002796,0.000000,0.0,0.000000,-1.890061e-07,0.0,0.0,0.0,1.890061e-07
Household,450,-148.458771,0.0,0.000000,0.000000,0.0,220.456733,0.0,0.0,0.0,8.0,-0.002796,0.006989,0.0,0.000000,0.000000e+00,0.0,0.0,0.0,-3.681404e-03

In [10]:
df2.loc[19].sum().map(lambda x: round(x, 4))

obj_id              7672.0
deposits              -0.0
loans                  0.0
bonds                  0.0
cash                  -0.0
advances              -0.0
equities               0.0
inventories            0.0
consumption            0.0
wages                  0.0
public_transfers      -0.0
taxes                  0.0
dep_interests          0.0
loan_interests         0.0
loan_defaults          0.0
bond_interests         0.0
cash_interests         0.0
adv_interests         -0.0
dividends              0.0
profit_transfers       0.0
dtype: float64